source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CAShuttleBus' do
 
  pod 'Masonry', '~> 1.0.2'
  pod 'YYText', '~> 1.0.7'
  pod 'JCAlertController', '~> 2.2.1'
  pod 'MJExtension', '~> 3.0.13'
  pod 'BaiduMapKit', '~> 3.4.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'YYCache', '~> 1.0.4'
  
end
